# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/faculty/Compilers/Project/YAPL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/faculty/Compilers/Project/YAPL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/faculty/Compilers/Project/YAPL/CMakeFiles /mnt/d/faculty/Compilers/Project/YAPL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/faculty/Compilers/Project/YAPL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yapl

# Build rule for target.
yapl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yapl
.PHONY : yapl

# fast build rule for target.
yapl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/build
.PHONY : yapl/fast

src/branching.o: src/branching.cpp.o
.PHONY : src/branching.o

# target to build an object file
src/branching.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/branching.cpp.o
.PHONY : src/branching.cpp.o

src/branching.i: src/branching.cpp.i
.PHONY : src/branching.i

# target to preprocess a source file
src/branching.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/branching.cpp.i
.PHONY : src/branching.cpp.i

src/branching.s: src/branching.cpp.s
.PHONY : src/branching.s

# target to generate assembly for a file
src/branching.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/branching.cpp.s
.PHONY : src/branching.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/controllers.o: src/controllers.cpp.o
.PHONY : src/controllers.o

# target to build an object file
src/controllers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/controllers.cpp.o
.PHONY : src/controllers.cpp.o

src/controllers.i: src/controllers.cpp.i
.PHONY : src/controllers.i

# target to preprocess a source file
src/controllers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/controllers.cpp.i
.PHONY : src/controllers.cpp.i

src/controllers.s: src/controllers.cpp.s
.PHONY : src/controllers.s

# target to generate assembly for a file
src/controllers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/controllers.cpp.s
.PHONY : src/controllers.cpp.s

src/expression.o: src/expression.cpp.o
.PHONY : src/expression.o

# target to build an object file
src/expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/expression.cpp.o
.PHONY : src/expression.cpp.o

src/expression.i: src/expression.cpp.i
.PHONY : src/expression.i

# target to preprocess a source file
src/expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/expression.cpp.i
.PHONY : src/expression.cpp.i

src/expression.s: src/expression.cpp.s
.PHONY : src/expression.s

# target to generate assembly for a file
src/expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/expression.cpp.s
.PHONY : src/expression.cpp.s

src/functions.o: src/functions.cpp.o
.PHONY : src/functions.o

# target to build an object file
src/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/functions.cpp.o
.PHONY : src/functions.cpp.o

src/functions.i: src/functions.cpp.i
.PHONY : src/functions.i

# target to preprocess a source file
src/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/functions.cpp.i
.PHONY : src/functions.cpp.i

src/functions.s: src/functions.cpp.s
.PHONY : src/functions.s

# target to generate assembly for a file
src/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/functions.cpp.s
.PHONY : src/functions.cpp.s

src/lex.yy.o: src/lex.yy.cc.o
.PHONY : src/lex.yy.o

# target to build an object file
src/lex.yy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/lex.yy.cc.o
.PHONY : src/lex.yy.cc.o

src/lex.yy.i: src/lex.yy.cc.i
.PHONY : src/lex.yy.i

# target to preprocess a source file
src/lex.yy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/lex.yy.cc.i
.PHONY : src/lex.yy.cc.i

src/lex.yy.s: src/lex.yy.cc.s
.PHONY : src/lex.yy.s

# target to generate assembly for a file
src/lex.yy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/lex.yy.cc.s
.PHONY : src/lex.yy.cc.s

src/parser.tab.o: src/parser.tab.cpp.o
.PHONY : src/parser.tab.o

# target to build an object file
src/parser.tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/parser.tab.cpp.o
.PHONY : src/parser.tab.cpp.o

src/parser.tab.i: src/parser.tab.cpp.i
.PHONY : src/parser.tab.i

# target to preprocess a source file
src/parser.tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/parser.tab.cpp.i
.PHONY : src/parser.tab.cpp.i

src/parser.tab.s: src/parser.tab.cpp.s
.PHONY : src/parser.tab.s

# target to generate assembly for a file
src/parser.tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yapl.dir/build.make CMakeFiles/yapl.dir/src/parser.tab.cpp.s
.PHONY : src/parser.tab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yapl"
	@echo "... src/branching.o"
	@echo "... src/branching.i"
	@echo "... src/branching.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/controllers.o"
	@echo "... src/controllers.i"
	@echo "... src/controllers.s"
	@echo "... src/expression.o"
	@echo "... src/expression.i"
	@echo "... src/expression.s"
	@echo "... src/functions.o"
	@echo "... src/functions.i"
	@echo "... src/functions.s"
	@echo "... src/lex.yy.o"
	@echo "... src/lex.yy.i"
	@echo "... src/lex.yy.s"
	@echo "... src/parser.tab.o"
	@echo "... src/parser.tab.i"
	@echo "... src/parser.tab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

